### ISSUE TITLE
Hello! This is an expert in Node.js Typescript Expert what you are looking for

### ISSUE THREAD

**Issue by wb-ts** [Taialt97/Tag-Flow#1]
Hello. I saw your posting on Upwork and I knew that you are looking for a developer who can help you with Organizer Plugin integration in your application.
I am confident in that project and would like to work with you in this awesome one.
You can check my github profile here. https://github.com/wb-ts
Please hire me.
Thank you.

**Comment by Taialt97** [comment]
Hi, 
Right now, I'm keeping it on low heat; maybe in the future, I could use your help with the development process.
Thanks.

**Comment by wb-ts** [comment]
Thanks. Could you please let me know your contact information such as email
or discord id?
